package gemcfadyen.drools_experimentation

import gemcfadyen.drools_experimentation.bankaccount.BankAccount;
import gemcfadyen.drools_experimentation.bankaccount.TransactionBook;
import gemcfadyen.drools_experimentation.bankaccount.TransactionType;

rule "should deposit money into bank account"

    when
    	bankAccount : BankAccount()
    	TransactionBook(transactionType == TransactionType.DEPOSIT, amount : amountForTransaction)
    then
        bankAccount.deposit(amount);

end

rule "should withdraw money from the bankaccount"
    when
		bankAccount : BankAccount()
		TransactionBook(transactionType == TransactionType.WITHDRAW, amount : amountForTransaction)
    then
        bankAccount.withdraw(amount);
end
