package gemcfadyen.drools_experimentation

global gemcfadyen.drools_experimentation.globals.GlobalResultObject result;  
//you dont need to import the global class explicitly even if you are using it on RHS and LHS

rule "should set the message property in the global result object"
when
    not(GlobalResultObject())
then
    result.setMessage("Global message has been set");
 end

rule "should set the message indicating a flag has been set on the object inserted in"
when
    GlobalResultObject(isSet == 10)
then
    result.setMessage("Global has a flag set so no message is returned");
end