package gemcfadyen.drools_experimentation;
import gemcfadyen.drools_experimentation.helloworld.Message;
global java.util.List list;

rule "Hello World" dialect "mvel"
when 
	m : Message (status == Message.HELLO, message : message)
then 
 	System.out.println(message)
	modify(m) {message = "Goodbye", status = Message.GOODBYE}
end

rule "Goodbye"
when
	Message (status == Message.GOODBYE, message : message)
then
list.add("hi");
	System.out.println(message);
end