template header

isWord
type
limit

package gemcfadyen.drools_experimentation
import gemcfadyen.drools_experimentation.templates.ParamSet;
global java.util.List list;

template "categorises words"

rule "should print out whether something is classified as a proper word @{row.rowNumber}" 

when
    p : ParamSet(isWord == @{isWord})

then
    System.out.println( "@{type}  has evaluated to:  @{isWord}");
    p.setLimit(-1);
    list.add("hi global added");   
   
end

end template
